spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  application:
    name: leoVegas
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
server:
  port: 8085
