INSERT INTO PLAYER (ID, BALANCE) VALUES (1, 5000);
INSERT INTO PLAYER (ID, BALANCE) VALUES (2, 5000);
INSERT INTO PLAYER (ID, BALANCE) VALUES (3, 5000);
INSERT INTO PLAYER (ID, BALANCE) VALUES (4, 30000);
INSERT INTO TRANSACTION_HISTORY (ID, PLAYER_ID, OPERATION_TYPE, OPERATION_AMOUNT) VALUES (1, 1, 'CREDIT', 55);