DROP TABLE IF EXISTS TRANSACTION_HISTORY;
DROP TABLE IF EXISTS PLAYER;


CREATE TABLE PLAYER (
                        ID INT AUTO_INCREMENT  PRIMARY KEY,
                        BALANCE DECIMAL(20) NOT NULL
);

CREATE TABLE TRANSACTION_HISTORY (
                        ID INT PRIMARY KEY,
                        PLAYER_ID INT NOT NULL,
                        OPERATION_TYPE VARCHAR(255) NOT NULL,
                        OPERATION_AMOUNT DECIMAL(20) NOT NULL
);
